name: ftps-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Nodejs 
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Build
        run: |
          npm install
          npm run build --if-present      
      
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./public/
          server-dir: ${{ secrets.FTP_DIR }}
